### ISSUE TITLE
inconsistent solution length when using `-h conflicts`

### ISSUE THREAD

**Issue by asarandi** [pbondoer/42-n_puzzle-rust#1]
hi Pierre,
i noticed this by chance and i thought you might want to know about this,

each time i run the program, the number of open/closed states changes,
but most importantly i noticed that when using the `conflicts` heuristic, sometimes it gives solutions of different lengths,

this was the test input:
```
# This puzzle is solvable
4
 2  3  4  8
12 14 13 10
 9  7  1  0
11  6 15  5
```

and i am also attaching a screenshot

greetings from fremont :)
-alex

<img width="1068" alt="screen shot 2018-12-30 at 6 49 30 pm" src="https://user-images.githubusercontent.com/32273214/50553867-cf8e8e80-0c64-11e9-86bd-5bcf42bd8414.png">

**Comment by pbondoer** [comment]
Hey Alex,

My first guess here would be the hash implementation in Rust. The logic we have is (as far as I know) completely deterministic, so the results should be the same for each run.

However it is my understanding (and I may be wrong in this, but I can't find much information about it) that you can't rely on Rust's `Hash` trait to produce the same result between binary executions. We rely on Rust's [`binary_heap`](https://doc.rust-lang.org/std/collections/binary_heap/) internally as our priority queue implementation. Since that relies on the `Hash` trait, it is therefore possibly non-deterministic, and would explain why the open/close state counts vary.

https://internals.rust-lang.org/t/stability-of-hash-values/2241

The strange part is that solutions lengths shouldn't change. Perhaps this means the `conflicts` heuristic isn't admissible like we first thought, since A* is guaranteed to find an optimal solution if the heuristic doesn't over-estimate...
